// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using CriandoTestes.GestaoUsuarios.Dados.EFCore.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CriandoTestes.GestaoUsuarios.Dados.EFCore.Migrations
{
  [ExcludeFromCodeCoverage]
  [DbContext(typeof(GestaoUsuariosContexto))]
  partial class GestaoUsuariosContextoModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.12")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("CriandoTestes.GestaoUsuarios.Dominio.Models.Usuario", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<DateTime>("DataNascimento")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Senha")
                      .IsRequired()
                      .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("Email")
                      .IsUnique();

            b.ToTable("Usuários", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
